on: push

jobs:
  build:
      name: Publish
      runs-on: ubuntu-latest
      strategy:
        fail-fast: true
        matrix:
          target:
            - x86_64-pc-windows-msvc
            - x86_64-apple-darwin	
            - x86_64-unknown-linux-gnu	
            - aarch64-unknown-linux-gnu	
      steps:
        - name: Set ENV
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - name: Build Project
        - uses: actions/checkout@v3
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            target: ${{ matrix.target }}
            override: true
        - uses: actions-rs/cargo@v1
          with:
            use-cross: true
            command: build
            args: --release --target=${{ matrix.target }}
        - name: Zip Product                 
          with:
            files: package/themes package/config.json README.md
            dest: spotify-np-v${{ env.RELEASE_VERSION }}.${{ matrix.target }}.zip
        - name: Create Release
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            draft: true
            files: |
              spotify-np-v${{ env.RELEASE_VERSION }}.${{ matrix.target }}.zip