on: [push, workflow_dispatch]

name: Publish (linux)
jobs:
  build:
    permissions:
      contents: write
      pull-requests: write

    name: Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          - x86_64-unknown-linux-gnu	
          - aarch64-unknown-linux-gnu	
    steps:
      - name: Checkout        
        uses: actions/checkout@v3

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install TOML
        run: npm install toml

      - name: Clone from Themes Repository
        run: git clone https://github.com/Nowaaru/spotify-np-themes.git themes
        
      - name: Build
        run: cargo build --release


      - name: Zip Product                 
        uses: vimtor/action-zip@v1
        with:
          files: README.md target/release/spotify-np package/ themes/
          dest: ${{ matrix.target }}.zip
          
      - name: Rename artifacts
        run: node .github/scripts/rename.js ${{ matrix.target }}.zip

      - name: Let the dogs out.
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: | 
            *.zip